name: 视频生成
file: json/video.json
output:
  file: "28"
args:
  #提示词
  prompt: "6.text"
  #负向提示词
  negative_prompt: "7.text"
  #图像宽度
  width: "40.width"
  #图像高度
  height: "40.height"
  #图像数量
  batch_size: "40.batch_size"
