name: Sync to Gitee

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      - name: Sync to Gitee
        run: |
          git remote add gitee  https://gitee.com/rachelos/comfyapi.git
          git push -f gitee ${{ github.ref_name }}

      - name: Clean up SSH
        run: |
          rm -rf ~/.ssh/id_rsa